### ISSUE TITLE
flutter_workmanager crashes app on S

### ISSUE THREAD

**Issue by adrianvintu** [ABausG/home_widget#63] opened 2022-01-08 10:49 UTC
Please consider updating the documentation to remove `flutter_workmanager` as it looks unmaintained and it straight up crashes on the emulator S as per https://github.com/fluttercommunity/flutter_workmanager/issues/352.

An easy replacement could be https://pub.dev/packages/android_alarm_manager_plus.

**Comment by Aderiani** [comment] 2022-01-14 16:11
I used the Android alarm manager for Anroid and it worked perfectly. But the problem is to find a substitute for IOS.

**Comment by ABausG** [comment] 2022-06-05 21:09
This is now fixed in the latest version. Also note that this only affects the example app and not the widget itself

**Closed by ABausG** 2022-06-05 21:09 UTC
