### ISSUE TITLE
Hey i am facing an issue in this plugin

### ISSUE THREAD

**Issue by KanhiyaParmar** [ABausG/home_widget#149] opened 2023-08-16 04:18 UTC
Unhandled Exception: Exception: Failed to render the widget: Exception: Failed to save screenshot to app group container: FileSystemException: Creation failed, path = 'null' (OS Error: Read-only file system, errno = 30)
#0      HomeWidget.renderFlutterWidget (package:home_widget/home_widget.dart:224:7)
<asynchronous suspension>

I used the same dart code and swift code of your plugin this error is due to when I send an icon in  HomeWidget.renderFlutterWidget().
but I only want to send textfiled data 

and this is my HomeWidgetExampleExtensionProfile.entitlements. file code 

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>com.apple.security.application-groups</key>
	<array>
		<string>group.com.vendor</string>
	</array>
</dict>
</plist>

I check k this step also but still facing this issue.
1. Add the capability to your provisioning Profile
2. Add App groups with the group Id to both your App Target and your new widget Target in Xcode
3. Make sure you use the correct group when accessing the data in the native code

I am facing this issue in the current new version and your ios folder code is old I am not sure about this can anyone try to now create this widget for ios?

**Comment by ABausG** [comment] 2024-07-15 20:23
I will close this for now.

If the issue is still persistent in the most recent version please re-open with a screenshot of your Xcode configuration to ensure the app group is set correctly for all build types in the runner target

**Closed by ABausG** 2024-07-15 20:23 UTC
